### PR TITLE
Adds support for Backbone.Model.unset

### LINKED ISSUE #1: Doesn't support Backbone.Model.unset.
It's currently not possible to remove properties from a StrictModel instance by using the unset method. When the unset method is called with an existing property, nothing happens - the property stay on like before.

### PR DESCRIPTION
**Pull request by snurra**
Fixes https://github.com/Oktavilla/backbone-despotism/issues/1

### CODE REVIEW

**Comment by snurra** [comment]
@martinlissmyr I had to rewrite the attribute mapping to check each attribute instead of only those defined in `props`, since it wasn't possible to include attributes with an undefined value otherwise.

**Comment by snurra** [comment]
Just realized that this probably won't work with the foreignKey transformation.

**Comment by snurra** [comment]
Couldn't find any fancy way to handle undefined properties within set **and** handle foreign keys at the same time, without doing a lot of overhead work. Made sure that Backbone.Model.set is called when unsetting attributes instead.

**Comment by martinlissmyr** [comment]
:+1:

**Pull request merged**
